<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SRS_Hotels.Data</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="src\BuildingBlocks\Abstractions\" />
    <Folder Include="src\BuildingBlocks\Extensions\" />
    <Folder Include="src\BuildingBlocks\Results\" />
    <Folder Include="src\BuildingBlocks\Pagination\" />
    <Folder Include="src\Infraestructure\Identity\" />
    <Folder Include="src\Infraestructure\Persistence\Configurations\" />
    <Folder Include="src\Infraestructure\Persistence\Contexts\" />
    <Folder Include="src\Infraestructure\Persistence\Migrations\" />
    <Folder Include="src\Infraestructure\Persistence\Seed\" />
    <Folder Include="src\Infraestructure\Shared\Services\" />
    <Folder Include="src\Modules\Accomodation\Contracts\" />
    <Folder Include="src\Modules\Accomodation\Domain\" />
    <Folder Include="src\Modules\Accomodation\Features\Ammenity\CreateAmmenity\" />
    <Folder Include="src\Modules\Accomodation\Features\Ammenity\DeleteAmmenity\" />
    <Folder Include="src\Modules\Accomodation\Features\Ammenity\GetAmmenityById\" />
    <Folder Include="src\Modules\Accomodation\Features\Ammenity\GetAmmenities\" />
    <Folder Include="src\Modules\Accomodation\Features\Ammenity\UpdateAmmenity\" />
    <Folder Include="src\Modules\Accomodation\Features\Floor\CreateFloor\" />
    <Folder Include="src\Modules\Accomodation\Features\Floor\DeleteFloor\" />
    <Folder Include="src\Modules\Accomodation\Features\Floor\GetFloors\" />
    <Folder Include="src\Modules\Accomodation\Features\Floor\GetFloorById\" />
    <Folder Include="src\Modules\Accomodation\Features\Floor\UpdateFloor\" />
    <Folder Include="src\Modules\Accomodation\Features\RoomCategory\CreateRoomCategory\" />
    <Folder Include="src\Modules\Accomodation\Features\RoomCategory\DeleteRoomCategory\" />
    <Folder Include="src\Modules\Accomodation\Features\RoomCategory\GetRoomCategoryById\" />
    <Folder Include="src\Modules\Accomodation\Features\RoomCategory\GetRoomCategories\" />
    <Folder Include="src\Modules\Accomodation\Features\RoomCategory\UpdateRoomCategory\" />
    <Folder Include="src\Modules\Accomodation\Features\RoomService\CreateRoomService\" />
    <Folder Include="src\Modules\Accomodation\Features\RoomService\DeleteRoomService\" />
    <Folder Include="src\Modules\Accomodation\Features\RoomService\GetRoomsServices\" />
    <Folder Include="src\Modules\Accomodation\Features\RoomService\GetRoomServiceById\" />
    <Folder Include="src\Modules\Accomodation\Features\RoomService\UpdateRoomService\" />
    <Folder Include="src\Modules\Accomodation\Features\Room\CreateRoom\" />
    <Folder Include="src\Modules\Accomodation\Features\Room\DeleteRoom\" />
    <Folder Include="src\Modules\Accomodation\Features\Room\GetRooms\" />
    <Folder Include="src\Modules\Accomodation\Features\Room\GetRoomById\" />
    <Folder Include="src\Modules\Accomodation\Features\Room\UpdateRoom\" />
    <Folder Include="src\Modules\Audit\Domain\" />
    <Folder Include="src\Modules\Audit\Features\GetUserActivity\" />
    <Folder Include="src\Modules\Audit\Features\GetAuditLogs\" />
    <Folder Include="src\Modules\Audit\Features\GetEntityHistory\" />
    <Folder Include="src\Modules\Authentication\Contracts\" />
    <Folder Include="src\Modules\Authentication\Domain\" />
    <Folder Include="src\Modules\Authentication\Features\Login\" />
    <Folder Include="src\Modules\Authentication\Features\Logout\" />
    <Folder Include="src\Modules\Authentication\Features\ChangePassword\" />
    <Folder Include="src\Modules\Authentication\Features\RefreshToken\" />
    <Folder Include="src\Modules\Bookings\Features\CreateBooking\" />
    <Folder Include="src\Modules\Bookings\Features\CancelBooking\" />
    <Folder Include="src\Modules\Bookings\Features\ConfirmBooking\" />
    <Folder Include="src\Modules\Bookings\Features\CheckIn\" />
    <Folder Include="src\Modules\Bookings\Features\CheckOut\" />
    <Folder Include="src\Modules\Bookings\Features\GetBooking\" />
    <Folder Include="src\Modules\Bookings\Features\GetBookings\" />
    <Folder Include="src\Modules\Bookings\Contracts\" />
    <Folder Include="src\Modules\Bookings\Features\BookingHistory\" />
    <Folder Include="src\BuildingBlocks\Behaviors\" />
    <Folder Include="src\BuildingBlocks\Exceptions\" />
    <Folder Include="src\Modules\Bookings\Features\UserBookingHistory\" />
    <Folder Include="src\Modules\CancellationPolicies\Domain\" />
    <Folder Include="src\Modules\CancellationPolicies\Contracts\" />
    <Folder Include="src\Modules\CancellationPolicies\Features\CreatePolicy\" />
    <Folder Include="src\Modules\CancellationPolicies\Features\DeletePolicy\" />
    <Folder Include="src\Modules\CancellationPolicies\Features\AddRule\" />
    <Folder Include="src\Modules\CancellationPolicies\Features\GetPolicies\" />
    <Folder Include="src\Modules\CancellationPolicies\Features\RemoveRule\" />
    <Folder Include="src\Modules\CancellationPolicies\Features\UpdatePolicy\" />
    <Folder Include="src\Modules\Customers\Domain\" />
    <Folder Include="src\Modules\Customers\Contracts\" />
    <Folder Include="src\Modules\Customers\Features\DeleteClient\" />
    <Folder Include="src\Modules\Customers\Features\GetClient\" />
    <Folder Include="src\Modules\Customers\Features\GetClients\" />
    <Folder Include="src\Modules\Customers\Features\SearchClients\" />
    <Folder Include="src\Modules\Customers\Features\UpdateClient\" />
    <Folder Include="src\Modules\Customers\Features\RegisterClient\" />
    <Folder Include="src\Modules\Employees\Contracts\" />
    <Folder Include="src\Modules\Employees\Features\CreateEmployee\" />
    <Folder Include="src\Modules\Employees\Features\DeactivateEmployee\" />
    <Folder Include="src\Modules\Employees\Features\AssignPosition\" />
    <Folder Include="src\Modules\Employees\Features\AssignShift\" />
    <Folder Include="src\Modules\Employees\Features\GetEmployee\" />
    <Folder Include="src\Modules\Employees\Features\GetEmployees\" />
    <Folder Include="src\Modules\Employees\Features\ReactivateEmployee\" />
    <Folder Include="src\Modules\Notifications\Domain\" />
    <Folder Include="src\Modules\Notifications\Contracts\" />
    <Folder Include="src\Modules\Notifications\Features\SendPromotionNotification\" />
    <Folder Include="src\Modules\Notifications\Features\SendCheckInReminder\" />
    <Folder Include="src\Modules\Notifications\Features\SendBookingConfirmation\" />
    <Folder Include="src\Modules\Notifications\Features\SendEmail\" />
    <Folder Include="src\Modules\Payments\Domain\" />
    <Folder Include="src\Modules\Payments\Features\CreatePayment\" />
    <Folder Include="src\Modules\Payments\Features\CancelPayment\" />
    <Folder Include="src\Modules\Payments\Features\GetPayment\" />
    <Folder Include="src\Modules\Payments\Features\GetPayments\" />
    <Folder Include="src\Modules\Payments\Features\GenerateInvoice\" />
    <Folder Include="src\Modules\Payments\Features\GetInvoices\" />
    <Folder Include="src\Modules\Payments\Features\RefundPayment\" />
    <Folder Include="src\Modules\Promotions\Domain\" />
    <Folder Include="src\Modules\Promotions\Features\CreatePromotion\" />
    <Folder Include="src\Modules\Promotions\Features\ActivatePromotion\" />
    <Folder Include="src\Modules\Promotions\Features\DeactivatePromotion\" />
    <Folder Include="src\Modules\Promotions\Features\CreateCoupon\" />
    <Folder Include="src\Modules\Promotions\Features\GetPromotion\" />
    <Folder Include="src\Modules\Promotions\Features\GetPromotions\" />
    <Folder Include="src\Modules\Promotions\Features\ValidateCoupon\" />
    <Folder Include="src\Modules\Promotions\Features\UpdatePromotion\" />
  </ItemGroup>

</Project>
